name: CI

on: 
   workflow_dispatch:
   
jobs:
   first_windo_machine:
      name: First window machine
      runs-on: windows-latest
      strategy:
       fail-fast: false
       matrix:
         runner: [0]

      steps:
       - uses: actions/checkout@v2
       - name: Download
         run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
       - name: Extract
         run: Expand-Archive ngrok.zip
       - name: Auth
         run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
         env:
           NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
           PASSWORD: ${{ secrets.PASSWORD }}
       - name: Setup Ngrok
         run: |
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
           Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
           Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText ${{ secrets.PASSWORD }} -Force)
       - name: Create Tunnel
         run: cmd.exe /c "START /b cmd /c .\ngrok\ngrok.exe tcp 3389 -log=stdout"
       - name: checking the ngrox url
         run: .\timeout.ps1
