name: YT

on: 
   workflow_dispatch:
   
jobs:
   first_windo_machine:
      name: First window machine
      runs-on: windows-latest
      strategy:
       fail-fast: false
       matrix:
         runner: [0]

      steps:
       - uses: actions/checkout@v2
       - name: Open YT
         run: |
           start-process "C:\Program Files\Google\Chrome\Application\chrome.exe" "https://www.youtube.com/watch?v=ie2b9riLssQ&list=PL1CKpJPRBDSQ3mJylAT7Cg26rHvRJW3PL"
       - name: YT time
         run: .\timeout.ps1
