name: YT

on: 
   workflow_dispatch:
   
jobs:
   first_windo_machine:
      name: First window machine
      runs-on: windows-latest
      strategy:
       fail-fast: false
       matrix:
         runner: [0,2,3,4,5]

      steps:
       - uses: actions/checkout@v2
       - name: Open YT
         run: |
           start-process "C:\Program Files\Google\Chrome\Application\chrome.exe" "https://youtu.be/3cwqTyldbjU"
       - name: YT time
         run: .\timeout.ps1
